name: HicSuntDracones
version: '${project.version}'
main: io.github.sawors.hicsuntdracones.HicSuntDracones
api-version: '1.20'
authors: [Sawors]
commands:
  map:
    usage: "Hic Sunt Dracones main command to access its features."
    permission: HicSuntDracones.map
permissions:
  map:
    default: op